name: docker联动
on: push

# permissions:
#   contents: write

jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4
      
      # - name: 安装依赖
      #   run: npm install

      # - name: 项目打包s
      #   run: npm run build

      # - name: 部署
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     branch: gh-pages
      #     folder: dist

      - name: 登录dockerhub
        uses: docker/login-action@v3 
        with: 
          username: lilebin
          password: kakaxi1998.
      
      - name: 构建并推送到docker
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: lilebin/vue-app
