name: Deploy Vue to Aliyun Windows Server

on:
  push:
    branches:
      - main   # 推送到 main 分支时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 4. 将 dist 上传到服务器
      - name: 更新文件到服务器
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist/*"
          target: "C:/inetpub/wwwroot/vue-app"
